version: '3.8'

services:
  app-shell:
    build: ./app-shell
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    profiles:
      - web
    networks:
      - instagram-network
    command: npm run dev -- --host 0.0.0.0 --port 3000

  scraper-backend:
    build: ./scraper/backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - CORS_ALLOWED_ORIGINS=http://localhost:5174,http://127.0.0.1:5174,http://dashboard:5173,http://localhost:5173,http://127.0.0.1:5173,http://scraper-frontend:5173
    volumes:
      - scraper_backend_data:/app/data
    profiles:
      - scraper
    networks:
      - instagram-network

# Ya no se necesita volumen para scraper_frontend

volumes:
  scraper_backend_data:

networks:
  instagram-network:
    driver: bridge 