version: '3.8'

services:
  app-shell:
    build: ./app-shell
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    profiles:
      - shell
    networks:
      - instagram-network
    command: npm run dev -- --host 0.0.0.0 --port 3000

  dashboard:
    build: ./dashboard_web
    ports:
      - "5174:5173"
    environment:
      - VITE_SCRAPER_API_URL=http://scraper-backend:8000
    profiles:
      - dashboard
    networks:
      - instagram-network

  scraper-backend:
    build: ./scraper/backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - CORS_ALLOWED_ORIGINS=http://localhost:5174,http://127.0.0.1:5174,http://dashboard:5173,http://localhost:5173,http://127.0.0.1:5173,http://scraper-frontend:5173
    volumes:
      - scraper_backend_data:/app/data
    profiles:
      - scraper
    networks:
      - instagram-network

  scraper-frontend:
    build: ./scraper/frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://scraper-backend:8000
      - NODE_ENV=development
    volumes:
      - scraper_frontend_svelte_kit:/app/.svelte-kit
    depends_on:
      - scraper-backend
    profiles:
      - scraper-ui
    networks:
      - instagram-network

volumes:
  scraper_backend_data:
  scraper_frontend_svelte_kit:

networks:
  instagram-network:
    driver: bridge 